#pragma once

/// USER_SECTION_START 1

/// USER_SECTION_END

// Debugging
#ifdef NDEBUG
	#define LOGGER_CONSOLE(msg)
	#define LOGGER_CONSOLE_FUNCTION(msg)
#else
	#include <iostream>

	#define LOGGER_DEBUG
	#define LOGGER_CONSOLE_STREAM std::cout

	#define LOGGER_CONSOLE(msg) LOGGER_CONSOLE_STREAM << msg;
	#define LOGGER_CONSOLE_FUNCTION(msg) LOGGER_CONSOLE_STREAM << __PRETTY_FUNCTION__ << " " << msg;
#endif

/// USER_SECTION_START 2

/// USER_SECTION_END

#ifdef LOGGER_PROFILING
	#include "easy/profiler.h"
	#include <easy/arbitrary_value.h> // EASY_VALUE, EASY_ARRAY are defined here

	#define LOGGER_PROFILING_BLOCK_C(text, color) EASY_BLOCK(text, color)
	#define LOGGER_PROFILING_NONSCOPED_BLOCK_C(text, color) EASY_NONSCOPED_BLOCK(text, color)
	#define LOGGER_PROFILING_END_BLOCK EASY_END_BLOCK
	#define LOGGER_PROFILING_FUNCTION_C(color) EASY_FUNCTION(color)
	#define LOGGER_PROFILING_BLOCK(text, colorStage) LOGGER_PROFILING_BLOCK_C(text,profiler::colors::  colorStage)
	#define LOGGER_PROFILING_NONSCOPED_BLOCK(text, colorStage) LOGGER_PROFILING_NONSCOPED_BLOCK_C(text,profiler::colors::  colorStage)
	#define LOGGER_PROFILING_FUNCTION(colorStage) LOGGER_PROFILING_FUNCTION_C(profiler::colors:: colorStage)
	#define LOGGER_PROFILING_THREAD(name) EASY_THREAD(name)

	#define LOGGER_PROFILING_VALUE(name, value) EASY_VALUE(name, value)
	#define LOGGER_PROFILING_TEXT(name, value) EASY_TEXT(name, value)

#else
	#define LOGGER_PROFILING_BLOCK_C(text, color)
	#define LOGGER_PROFILING_NONSCOPED_BLOCK_C(text, color)
	#define LOGGER_PROFILING_END_BLOCK
	#define LOGGER_PROFILING_FUNCTION_C(color)
	#define LOGGER_PROFILING_BLOCK(text, colorStage)
	#define LOGGER_PROFILING_NONSCOPED_BLOCK(text, colorStage)
	#define LOGGER_PROFILING_FUNCTION(colorStage)
	#define LOGGER_PROFILING_THREAD(name)

	#define LOGGER_PROFILING_VALUE(name, value)
	#define LOGGER_PROFILING_TEXT(name, value)
#endif

// Special expantion tecniques are required to combine the color name
#define CONCAT_SYMBOLS_IMPL(x, y) x##y
#define CONCAT_SYMBOLS(x, y) CONCAT_SYMBOLS_IMPL(x, y)



// Different color stages
#define LOGGER_COLOR_STAGE_1 50
#define LOGGER_COLOR_STAGE_2 100
#define LOGGER_COLOR_STAGE_3 200
#define LOGGER_COLOR_STAGE_4 300
#define LOGGER_COLOR_STAGE_5 400
#define LOGGER_COLOR_STAGE_6 500
#define LOGGER_COLOR_STAGE_7 600
#define LOGGER_COLOR_STAGE_8 700
#define LOGGER_COLOR_STAGE_9 800
#define LOGGER_COLOR_STAGE_10 900
#define LOGGER_COLOR_STAGE_11 A100 
#define LOGGER_COLOR_STAGE_12 A200 
#define LOGGER_COLOR_STAGE_13 A400 
#define LOGGER_COLOR_STAGE_14 A700 


// General
#define LOGGER_GENERAL_PROFILING_COLORBASE Cyan
#define LOGGER_GENERAL_PROFILING_BLOCK_C(text, color) LOGGER_PROFILING_BLOCK_C(text, color)
#define LOGGER_GENERAL_PROFILING_NONSCOPED_BLOCK_C(text, color) LOGGER_PROFILING_NONSCOPED_BLOCK_C(text, color)
#define LOGGER_GENERAL_PROFILING_END_BLOCK LOGGER_PROFILING_END_BLOCK;
#define LOGGER_GENERAL_PROFILING_FUNCTION_C(color) LOGGER_PROFILING_FUNCTION_C(color)
#define LOGGER_GENERAL_PROFILING_BLOCK(text, colorStage) LOGGER_PROFILING_BLOCK(text, CONCAT_SYMBOLS(LOGGER_GENERAL_PROFILING_COLORBASE, colorStage))
#define LOGGER_GENERAL_PROFILING_NONSCOPED_BLOCK(text, colorStage) LOGGER_PROFILING_NONSCOPED_BLOCK(text, CONCAT_SYMBOLS(LOGGER_GENERAL_PROFILING_COLORBASE, colorStage))
#define LOGGER_GENERAL_PROFILING_FUNCTION(colorStage) LOGGER_PROFILING_FUNCTION(CONCAT_SYMBOLS(LOGGER_GENERAL_PROFILING_COLORBASE, colorStage))
#define LOGGER_GENERAL_PROFILING_VALUE(name, value) LOGGER_PROFILING_VALUE(name, value)
#define LOGGER_GENERAL_PROFILING_TEXT(name, value) LOGGER_PROFILING_TEXT(name, value)


/// USER_SECTION_START 3

/// USER_SECTION_END
