#pragma once

// Profiling
#ifdef LOGGER_PROFILING
#include <easy/profiler.h>

#define LOGGERP_BLOCK(text, color) EASY_BLOCK(text, profiler::colors:: color)
#define LOGGERP_END_BLOCK EASY_END_BLOCK
#define LOGGERP_FUNCTION(color) EASY_FUNCTION(profiler::colors:: color)
#define LOGGERP_THREAD(name) EASY_THREAD(name)
#else
#define LOGGERP_BLOCK(text, color)
#define LOGGERP_END_BLOCK
#define LOGGERP_FUNCTION(color)
#define LOGGERP_THREAD(name)
#endif
#define CONCAT_SYMBOLS_IMPL(x, y) x##y
#define CONCAT_SYMBOLS(x, y) CONCAT_SYMBOLS_IMPL(x, y)

// Different color stages
#define LOGGERP_COLOR_STAGE_1 50
#define LOGGERP_COLOR_STAGE_2 100
#define LOGGERP_COLOR_STAGE_3 200
#define LOGGERP_COLOR_STAGE_4 300
#define LOGGERP_COLOR_STAGE_5 400
#define LOGGERP_COLOR_STAGE_6 500
#define LOGGERP_COLOR_STAGE_7 600
#define LOGGERP_COLOR_STAGE_8 700
#define LOGGERP_COLOR_STAGE_9 800
#define LOGGERP_COLOR_STAGE_10 900
#define LOGGERP_COLOR_STAGE_11 A100 
#define LOGGERP_COLOR_STAGE_12 A200 
#define LOGGERP_COLOR_STAGE_13 A400 
#define LOGGERP_COLOR_STAGE_14 A700 

// Colors for XXX 
#define LOGGERP_XXX_COLORBASE Green
#define LOGGERP_XXX_COLOR_1  CONCAT_SYMBOLS(LOGGERP_XXX_COLORBASE , LOGGERP_COLOR_STAGE_1 )
#define LOGGERP_XXX_COLOR_2  CONCAT_SYMBOLS(LOGGERP_XXX_COLORBASE , LOGGERP_COLOR_STAGE_2 )
#define LOGGERP_XXX_COLOR_3  CONCAT_SYMBOLS(LOGGERP_XXX_COLORBASE , LOGGERP_COLOR_STAGE_3 )
#define LOGGERP_XXX_COLOR_4  CONCAT_SYMBOLS(LOGGERP_XXX_COLORBASE , LOGGERP_COLOR_STAGE_4 )
#define LOGGERP_XXX_COLOR_5  CONCAT_SYMBOLS(LOGGERP_XXX_COLORBASE , LOGGERP_COLOR_STAGE_5 )
#define LOGGERP_XXX_COLOR_6  CONCAT_SYMBOLS(LOGGERP_XXX_COLORBASE , LOGGERP_COLOR_STAGE_6 )
#define LOGGERP_XXX_COLOR_7  CONCAT_SYMBOLS(LOGGERP_XXX_COLORBASE , LOGGERP_COLOR_STAGE_7 )
#define LOGGERP_XXX_COLOR_8  CONCAT_SYMBOLS(LOGGERP_XXX_COLORBASE , LOGGERP_COLOR_STAGE_8 )
#define LOGGERP_XXX_COLOR_9  CONCAT_SYMBOLS(LOGGERP_XXX_COLORBASE , LOGGERP_COLOR_STAGE_9 )
#define LOGGERP_XXX_COLOR_10 CONCAT_SYMBOLS(LOGGERP_XXX_COLORBASE , LOGGERP_COLOR_STAGE_10)
#define LOGGERP_XXX_COLOR_11 CONCAT_SYMBOLS(LOGGERP_XXX_COLORBASE , LOGGERP_COLOR_STAGE_11) 
#define LOGGERP_XXX_COLOR_12 CONCAT_SYMBOLS(LOGGERP_XXX_COLORBASE , LOGGERP_COLOR_STAGE_12) 
#define LOGGERP_XXX_COLOR_13 CONCAT_SYMBOLS(LOGGERP_XXX_COLORBASE , LOGGERP_COLOR_STAGE_13) 
#define LOGGERP_XXX_COLOR_14 CONCAT_SYMBOLS(LOGGERP_XXX_COLORBASE , LOGGERP_COLOR_STAGE_14) 
